FROM python:3.7-slim
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY florescielo-api requirements.txt ./florescielo-api/
CMD exec gunicorn --bind :$PORT --workers 1 --worker-class uvicorn.workers.UvicornWorker --threads 8 --access-logfile /var/log/gunicorn.log florescielo-api.main:app
